### ISSUE TITLE
ChordPro directive lost in chord over lyrics mode and back

### ISSUE THREAD

**Issue by faniry6** [artutra/OpenChord#107]
**Describe the bug**
In songedit mode, chordpro directive such as ``` {start_of_verse} ... {end_of_verse}``` are gone when going from  chord over lyrics  to chordpro  

**To Reproduce**
1. Go to a 'song'
2. Go to 'edit mode'
3. Switch to 'chord over lyrics'
4. Do some edit
5. Go back to chordpro mode

**Expected behavior**
Directive should be preserve or alternatively, editing in ```chord over lyrics``` is avoided and should only serve as preview. Some weird behavior also occurs when switching back and forth between chordpro and chord over lyrics mode several times (e.g: increase in vertical spacing)

**Comment by artutra** [comment]
Some people actually complain to me about it happening on the edit screen. To fix this I will add a preview button exclusively to see how the song will be displayed.
But at the same time I want to allow more lay people to edit in the "Chords Over Lyrics" format so I’ll add a button to choose from before I start editing.
Do you have any other suggestions?

**Comment by faniry6** [comment]
I think that's a good idea. Having the switch would best but I guess that's a lot of work.
