### ISSUE TITLE
Previous/Next page button

### ISSUE THREAD

**Issue by andrelopespereira** [artutra/OpenChord#91]
In some cases, the song is too quick or too slow to follow the auto scroll speed.

It could be useful if the app have 2 buttons on screen to move to next/previous page of the song.

**Comment by artutra** [comment]
It looks like the same feature request of the other issue #51 , right?

**Comment by andrelopespereira** [comment]
True!...
But touching bottom side of the screen, scroll down; touching upper side, scroll up.

**Comment by artutra** [comment]
Closed with #109
