### ISSUE TITLE
Songs in playlists not sorted

### ISSUE THREAD

**Issue by andrelopespereira** [artutra/OpenChord#92]
The songs in the playlist aren't sorted.
They are shown in music creation order.

It could easier to sort by name.

**Comment by artutra** [comment]
Did you try to press on the "Edit Playlist" button?
![image](https://user-images.githubusercontent.com/15269475/82915532-3fcb3d80-9f47-11ea-80a0-10095263ae81.png)
It you enable you to reorder the songs as you like
![image](https://user-images.githubusercontent.com/15269475/82915584-52457700-9f47-11ea-8843-3ad5717cb6f3.png)

**Comment by andrelopespereira** [comment]
Yes, I can reorder manually. And I understand what you think now: Pre-select a music order to sing!
What about a button "sort alphabetically"?

**Comment by artutra** [comment]
Yeah I still like the idea of the "Sort By Title" button, I was just wondering if the custom ordering was working correctly

**Comment by artutra** [comment]
Closed on v0.5.0
