### ISSUE TITLE
Import/Export .openchord files

### ISSUE THREAD

**Issue by andrelopespereira** [artutra/OpenChord#93]
In order to ensure the personal content, it would be very usefull if the app has a import/export data feature to backup/restore songs.

To export, each song could be a TXT file and a ZIP file to group all.
To import, could be a single TXT file or a folder with 2 or more TXT files.

**Comment by artutra** [comment]
Great ideia! It will work for backup and for sharing songs to other users

**Comment by artutra** [comment]
I separated this issue in two parts:
- import/export for backup, for security
- import chordpro files, so you can edit your songs on your computer #112

**Comment by artutra** [comment]
Closed with #103
